Hungry Cow
tiffanygan/usaco pull request #3
Opened 2023-08-15 03:40 UTC by tiffanygan

2023-08-15 03:58 UTC, yugan2005 requested changes

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +    int numDel;
`numDel` should be `numDelivery`, `del` has specific meaning in CS world, should avoid.

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +        pair<ll, int> temp = {day, amt};
don't need create a pair then `emplace_back`, one important advantage of `emplace_back` is that it can create the needed object in-place, thus efficient.

Change next line: `deliveries.emplace_back(day, amt);`

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +    set<ll> delDays;
`delDays` -> `deliveryDays` The same reason as above

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +    ll numEaten = 1;
Add comments that these two lines set up the initial condition corresponding to the first delivery day.

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +        if (numLeft - numDaysPassed > 0) {
change to `numLeft > numDaysPassed` make the intention clearer.

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +        ll numDaysPassed = deliveries[i].first - deliveries[i - 1].first - 1;
`numDaysPassed` should be `daysInBetween`

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +        } else if (numLeft > 0) {
`numLeft > 0` condition probably not needed.
It is always much easier to understand if you have the if / else branches based on the same logic, such as: 
```
if (A>B) {
  ...
} else if (A<B) {
  ...
} else {
  ...
}
```
 Or for more complex one:
```
if (A>B && C>D) {
  ...
} else if (A>B && C<=D) {
  ...
} else if (A<=B && C>D) {
  ...
} else {
  ...
}
```

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +    for (int i = 1; i < numDel; ++i) {
add variables `prevDeliveryDay` and `currDeliveryDay` and avoid repetitive handling the array indexes.

2023-08-15 03:58 UTC, yugan2005 commented on src/hungrycow.cpp
> +        } else if (numLeft > 0) {
`numLeft` always >= 0

2023-08-16 00:02 UTC, tiffanygan commented on src/hungrycow.cpp
> +    int numDel;
agree

2023-08-16 00:02 UTC, tiffanygan commented on src/hungrycow.cpp
> +        pair<ll, int> temp = {day, amt};
agree

2023-08-16 00:02 UTC, tiffanygan commented on src/hungrycow.cpp
> +    set<ll> delDays;
agree

2023-08-16 00:02 UTC, tiffanygan commented on src/hungrycow.cpp
> +    ll numEaten = 1;
agree

2023-08-16 00:03 UTC, tiffanygan commented on src/hungrycow.cpp
> +        if (numLeft - numDaysPassed > 0) {
agree

2023-08-16 00:03 UTC, tiffanygan commented on src/hungrycow.cpp
> +        ll numDaysPassed = deliveries[i].first - deliveries[i - 1].first - 1;
agree

2023-08-16 00:03 UTC, tiffanygan commented on src/hungrycow.cpp
> +        } else if (numLeft > 0) {
agree

2023-08-16 00:03 UTC, tiffanygan commented on src/hungrycow.cpp
> +    for (int i = 1; i < numDel; ++i) {
agree

2023-08-16 00:03 UTC, tiffanygan commented on src/hungrycow.cpp
> +        } else if (numLeft > 0) {
agree

2023-08-16 00:47 UTC, yugan2005 requested changes

2023-08-16 00:47 UTC, yugan2005 commented on src/hungrycow.cpp
> +    if (deliveries[numDeliveries - 1].first < numDays) {
You can keep using `prevDeliveryDay` and `currDeliveryDay` here, which will make this paragraph of code much more readable and consistent

2023-08-16 01:54 UTC, tiffanygan commented on src/hungrycow.cpp
> +    if (deliveries[numDeliveries - 1].first < numDays) {
agree

2023-08-16 04:30 UTC, yugan2005 requested changes

2023-08-16 04:30 UTC, yugan2005 commented on src/hungrycow.cpp
> +    if (currDeliveryDay < numDays) {
I will write as follow:

```c++
ll daysToEnd = numDays - prevDeliveryDay;
if (daysToEnd > 0) {
    if (numLeft > daysToEnd) {
            numEaten += daysToEnd;
    } else {
            numEaten += numLeft;
    }
```
comments:
1. as pointed out before, `if (numLeft > 0 )` has no meaning
2. keep the same coding style make the code much easier to understand. The new code matches the logic and style in Line 32 to Line 39

2023-08-16 05:05 UTC, tiffanygan commented on src/hungrycow.cpp
> +    if (currDeliveryDay < numDays) {
agree

2023-08-20 03:05 UTC, yugan2005 approved these changes
lgtm

2023-08-20 04:06 UTC, merged