speeding ticket
tiffanygan/usaco pull request #4
Opened 2023-08-15 23:53 UTC by tiffanygan

2023-08-16 00:42 UTC, yugan2005 requested changes

2023-08-16 00:42 UTC, yugan2005 commented on doc/index.md
> +* Use two pointers, one for Bessie and one for limit information
Add the following details,

"Use ... information. While transverse all ordered landmarks, decide whether the pointer of bessie or the pointer of limit or both need proceed. Also pay attention, that `>` or `<` should be used instead of `>=`, `<=` in line 46, 47"

Also add another bullet point:
* use `struct` instead of `pair` to make code more readable (without performance penalty)

2023-08-16 00:42 UTC, yugan2005 commented on src/speedingticket.cpp
> +    landmarks.emplace(0);
You don't need add `0`. Adding `0` actual is not right in this logic

2023-08-16 01:51 UTC, tiffanygan commented on doc/index.md
> +* Use two pointers, one for Bessie and one for limit information
agree

2023-08-16 01:51 UTC, tiffanygan commented on src/speedingticket.cpp
> +    landmarks.emplace(0);
agree

2023-08-16 04:34 UTC, yugan2005 requested changes

2023-08-16 04:34 UTC, yugan2005 commented on doc/index.md
> +* Use two pointers, one for Bessie and one for limit information
You should not just simply copy and paste my comments, but write your own. While you copying my comments, you lost the formatting strings such as the backtick ` around my inline code `struct`, `pair` etc.

2023-08-16 04:34 UTC, yugan2005 commented on doc/index.md
> +* Use struct instead of pair to make code more readable (without performance penalty)
use backtick around inline code

2023-08-16 04:56 UTC, tiffanygan commented on doc/index.md
> +* Use two pointers, one for Bessie and one for limit information
agree

2023-08-16 04:56 UTC, tiffanygan commented on doc/index.md
> +* Use struct instead of pair to make code more readable (without performance penalty)
agree

2023-08-20 03:06 UTC, yugan2005 approved these changes
lgtm

2023-08-20 04:03 UTC, merged